name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
          export VERSION=`grep CMARK_VERSION_STRING ext/cmark_version.h | awk '{print $3}'`
          export REVISION=1
          sed -e "s/_VERSION/${VERSION}/g; s/_REVISION/${REVISION}/g" < rockspec.in > cmark-${VERSION}-${REVISION}.rockspec
          luarocks --local make cmark-${VERSION}-${REVISION}.rockspec

  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
          export VERSION=`grep CMARK_VERSION_STRING ext/cmark_version.h | awk '{print $3}'`
          export REVISION=1
          sed -e "s/_VERSION/${VERSION}/g; s/_REVISION/${REVISION}/g" < rockspec.in > cmark-${VERSION}-${REVISION}.rockspec
          luarocks --local make cmark-${VERSION}-${REVISION}.rockspec

